export const devAdsData = [
  {
    developer_name: "شركة الأمل العقارية",
    description: "مشروعات سكنية في القاهرة الجديدة.",
    project_types: ["سكني", "فاخر"],
    image: "/2.png",
    phone: "01012345678",
    location: "القاهرة الجديدة",
    website_url: "https://alamal-dev.com",
    price_start_from: 1200000,
    price_end_to: 2500000,
    userId: "dev-user-1",
    type_of_user: "developer",
    ads: true,
    adExpiryTime: Date.now() + 15 * 24 * 60 * 60 * 1000,
  },
  {
    developer_name: "دار العقار",
    description: "مشاريع استثمارية وتجارية متميزة.",
    project_types: ["تجاري", "استثماري"],
    image: "/2.png",
    phone: "01234567890",
    location: "مدينة نصر",
    website_url: "https://dar-alaqar.com",
    price_start_from: 800000,
    price_end_to: 2000000,
    userId: "dev-user-2",
    type_of_user: "developer",
    ads: true,
    adExpiryTime: Date.now() + 20 * 24 * 60 * 60 * 1000,
  },
  {
    developer_name: "أبراج النور",
    description: "مباني شاهقة بأسعار تنافسية.",
    project_types: ["أبراج", "سكني"],
    image: "/2.png",
    phone: "01111111111",
    location: "العاشر من رمضان",
    website_url: "https://elnour-towers.com",
    price_start_from: 600000,
    price_end_to: 1800000,
    userId: "dev-user-3",
    type_of_user: "developer",
    ads: true,
    adExpiryTime: Date.now() + 10 * 24 * 60 * 60 * 1000,
  },
];
